name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
      - '**.svg'
      - '**/docs/**'
      - 'rusty-db/assign/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
      - '**.svg'
      - '**/docs/**'
      - 'rusty-db/assign/**'
  schedule:
    - cron: '0 4 * * *'

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Check
        run: cargo check --all --all-targets

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Tests
        run: cargo test --all --all-features --verbose
